language: python 

python: 
- "3.6.6"

env: 
- DJANGO=2.0 DB=postgres

before_install: 
- cd decide

install: 
- pip install -r ../requirements.txt

before_script:
 - cp local_settings.travis.py local_settings.py
 - psql -c "create user decide with password 'decide'" -U postgres
 - psql -c "create database decide owner decide" -U postgres
 - python manage.py migrate

script: 
- python manage.py test

services:
  - postgresql

addons:
  postgresql: "9.6"

global:
  - PGPORT=5432

notifications:
  email: false